[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra -q --tb=short
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning
